// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.Watson.subsystems;

import org.usfirst.frc3244.Watson.RobotMap;
import org.usfirst.frc3244.Watson.commands.*;
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.RobotDrive;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {

    private final CANTalon motor_Left_Front = RobotMap.driveTrainMotor_Left_Front;
    private final CANTalon motor_Left_Rear = RobotMap.driveTrainMotor_Left_Rear;
    private final CANTalon motor_Right_Front = RobotMap.driveTrainMotor_Right_Front;
    private final CANTalon motor_Right_Rear = RobotMap.driveTrainMotor_Right_Rear;
    private final RobotDrive robotDrive41 = RobotMap.driveTrainRobotDrive41;
    private final AnalogGyro analogGyro1 = RobotMap.driveTrainAnalogGyro1;

  
    public void initDefaultCommand() {
       

        setDefaultCommand(new Drive_Robot_Robot_Oriented_Mecanum());

      
    }
}

