// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.HungryVonHippo.commands;
import edu.wpi.first.wpilibj.Joystick.AxisType;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc3244.HungryVonHippo.Robot;

/**
 *
 */
public class FlyWheel_Run extends Command {
	private boolean setupEN = true;
	private double m_power;
	public static final double PIN_LEFT_FUEL_POWER = 75.0;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public FlyWheel_Run(double power) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.flyWheel);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        m_power = power;
        if(setupEN){
    		SmartDashboard.putNumber("FlyWheel SP", .8);
    	}
        
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	
    	Robot.vision_hardware.My_Left_Forward(true);
    	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if(setupEN){
    		m_power = SetUp();
    	}

    	Robot.flyWheel.My_FlyWheel_Run(m_power);
    	double m_fw_acct = Robot.flyWheel.My_GetFlyWheelSpeed_Acctual();
    	double m_fw_target =Robot.flyWheel.My_GetFlyWheelSpeed_Target();
    	if(m_fw_acct > (m_fw_target-(m_fw_target*.10))){
    		Robot.flyWheel.My_Fuel_Indexer_Run(1);
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.vision_hardware.My_Left_Forward(false);
    	Robot.flyWheel.My_FlyWheel_Stop();
    	Robot.flyWheel.My_Fuel_Indexer_Run(0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
    
    private double SetUp(){
    	return SmartDashboard.getNumber("FlyWheel SP", m_power);
    }
}
