// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.TalonSRXTest;

import java.awt.Choice;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import com.ctre.CANTalon.FeedbackDevice;
import com.ctre.CANTalon.TalonControlMode;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon talonControlerMotorLeft;
    public static CANTalon talonControlerMotorRight;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        
        talonControlerMotorLeft = new CANTalon(2);
        LiveWindow.addActuator("TalonControler", "Motor Left", talonControlerMotorLeft);
        
        talonControlerMotorLeft.setFeedbackDevice(FeedbackDevice.CtreMagEncoder_Absolute);
        
        talonControlerMotorLeft.reverseSensor(true);
        
        talonControlerMotorLeft.changeControlMode(TalonControlMode.PercentVbus);
        
        
        talonControlerMotorRight = new CANTalon(1);
        LiveWindow.addActuator("TalonControler", "Motor Left", talonControlerMotorLeft);
        
        talonControlerMotorRight.setFeedbackDevice(FeedbackDevice.CtreMagEncoder_Absolute);
        
        //talonControlerMotorLeft.reverseSensor(true);
        
        talonControlerMotorLeft.changeControlMode(TalonControlMode.PercentVbus);;
        

 
    }
}
