// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.Watson;

import org.usfirst.frc3244.Watson.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.InternalButton;
import edu.wpi.first.wpilibj.buttons.JoystickButton;

import org.usfirst.frc3244.Watson.subsystems.*;
import org.usfirst.util.JoystickPOVButton;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
////CREATING BUTTONS
   public static Joystick xbox_1;
   public JoystickButton a_1;
   public JoystickButton b_1;
   public JoystickButton x_1;
   public JoystickButton y_1;
   public JoystickButton lb_1;
   public JoystickButton rb_1;
   public JoystickButton start_1;
   public JoystickButton reset_1;
   private static final JoystickPOVButton DRIVER_PAD_D_PAD_UP = new JoystickPOVButton(xbox_1, 0);
   private static final JoystickPOVButton DRIVER_PAD_D_PAD_RIGHT = new JoystickPOVButton(xbox_1, 90);
   private static final JoystickPOVButton DRIVER_PAD_D_PAD_DOWN = new JoystickPOVButton(xbox_1, 180);
   private static final JoystickPOVButton DRIVER_PAD_D_PAD_LEFT = new JoystickPOVButton(xbox_1, 270);
  
   
   public Joystick xbox_2;
   public JoystickButton a_2;
   public JoystickButton b_2;
   public JoystickButton x_2;
   public JoystickButton y_2;
   public JoystickButton lb_2;
   public JoystickButton rb_2;
   public JoystickButton start_2;
   public JoystickButton reset_2;
   
   
   public Joystick launchPad;
   public JoystickButton btn1;
   public JoystickButton toggleSwitch;
   
   //InternalButtons
   public InternalButton example;

   
    public OI() {
    	setUp_Controler_Xbox_1();
    	setUp_Controler_Xbox_2();
    	setUp_Controler_LaunchPad();
    	setUp_SmartDashboard_Buttons();
    }
    
    private void setUp_Controler_Xbox_1(){
    	xbox_1 = new Joystick(0);
    	
        a_1 = new JoystickButton(xbox_1, 1);
        a_1.whileHeld(new IntakeJog());
        
        b_1 = new JoystickButton(xbox_1, 2);
        b_1.whileHeld(new Winch_Jog(1));
        
        x_1 = new JoystickButton(xbox_1, 3);
        //x_1.whileHeld(new CMD());
        
        y_1 = new JoystickButton(xbox_1, 4);
        y_1.whileHeld(new Winch_Jog(.5));
        
        lb_1 = new JoystickButton(xbox_1, 5);
        lb_1.whileHeld(new WristJogDown());

        rb_1 = new JoystickButton(xbox_1, 6);
        rb_1.whileHeld(new WristJogUp());

        reset_1 = new JoystickButton(xbox_1, 7);
        //reset_1.whenPressed(new CMD());
        
        start_1 = new JoystickButton(xbox_1, 8);
        //start_1.whileHeld(new CMD());
    }
    
    private void setUp_Controler_Xbox_2(){
    	xbox_2 = new Joystick(1);
    	
    	a_2 = new JoystickButton(xbox_2, 1);
        //a_2.whileHeld(new CMD());
        
        b_2 = new JoystickButton(xbox_2, 2);
        //b_2.whileHeld(new CMD());
        
    	x_2 = new JoystickButton(xbox_2, 3);
        //x_2.whileHeld(new CMD());
       
        y_2 = new JoystickButton(xbox_2, 4);
        //y_2.whileHeld(new CMD());
        
        lb_2 = new JoystickButton(xbox_2, 5);
        //lB_2.whileHeld(new CMD());
        
        rb_2 = new JoystickButton(xbox_2, 6);
        //rB_2.whileHeld(new CMD());
        
        reset_2 = new JoystickButton(xbox_2, 7);
        //reset_2.whenPressed(new CMD());
        
        start_2 = new JoystickButton(xbox_2, 8);
        //start_2.whileHeld(new CMD());
       
    }
    
    private void setUp_Controler_LaunchPad(){
    	launchPad = new Joystick(2);
        
    	btn1 = new JoystickButton(launchPad, 1);
    	//btn1.whenPressed(new CMD());
    	
    	toggleSwitch = new JoystickButton(launchPad, 7);
        //toggleSwitch.whileHeld(new Drive_Robot_Robot_Field_Oriented_Mecanum());
    	
    }
    
    private void setUp_SmartDashboard_Buttons(){
    	SmartDashboard.putNumber("Claw Shot Setpoint",15);
    	example = new InternalButton();
    	//example.whileHeld(new CMD());
    }
   

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getxbox_1() {
        return xbox_1;
    }

    public Joystick getxbox_2() {
        return xbox_2;
    }

    public Joystick getlaunchPad() {
        return launchPad;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

